### ISSUE TITLE
Made a pre-release Windows port version of this project

### ISSUE THREAD

**Issue by dewcked** [JohnCiubuc/StreamLinkerino#74]
https://github.com/dewcked/StreamLinkerino/releases

There's still lot to change, and I'm kinda new to Qt framework so I'm working on it to make it better 😄 .

**Comment by JohnCiubuc** [comment]
Awesome stuff man, wishing you the best!

I took some inspiration and added the json reading for channel switching into the testing branch here. But the delay on switch (due to json writing frequency) is terrible. Trying to make a hack around detecting mouse clicks on application but seems to not be going well due to X's rendering. Got any suggestions on how to improve that channel switching in the most non invasive way possible?

**Comment by dewcked** [comment]
> But the delay on switch (due to json writing frequency) is terrible.

I measured code executing time of json reading part in my code. Compared to bare streamlink, the delay did not increase noticeably. More than 95% of delays are assumed to be caused by re-loading streams.

> Trying to make a hack around detecting mouse clicks on application but seems to not be going well due to X's rendering.

I don't have any knowledge about X's renderer. So I'm not sure if it works simillar as Windows's one. The most important purpose of forking and redesigning this project was to reduce dependencies and modularize by making Chatterino patches not necessary. I considered API hooking to receive channel information, but it wasn't a simple method.

The easiest way to receive channel information without using methods such as API hooking was to load the official json file. I'd say Current method is not stable (It fails to remember the channel information selected at a very very low frequency). Also it needs restarting Chatterino to save information into json file. (There is no hard evidence as to when that is stored)

Can X window system get tab lists (which are channel lists) from window handler? Because in Windows, it was not possible without hooking or dll injection.

**Comment by JohnCiubuc** [comment]
I agree with your mission and fully support it!

Actual switching form the json file is pretty instant on my end, so that's not an issue. Issue is that chatterino writes into the json file around 10s or so after a new channel is selected which is annoying. Workaround is to close the app when channel switching which allows for immediate saving. I assume that's what you're doing on your end with the custom context menu to load a channel.

I also considered api hooking but it does seem to be annoying. Perhaps hooking onto the requests chatterino sends to twitch for channel information could be the way to go, but it's definitely annoying.

Also checked on embedded chatterino, consumes events as it's a separate application but even so i cant' lower it's Z-order in the application on embed to put an invisible widget over it to track mouse events. A potential solution is to do a global mouse hook and popup a custom menu when a click is done over the application's geometry, but that's slightly invasive so I don't know if standard users would be down to use it.

**Comment by JohnCiubuc** [comment]
So I managed to hack together a temporary, but acceptable solution:

https://streamable.com/jzdjpg

Buggy, but at least it switches pretty fast now without having to create a custom right click menu, overlay, or needing to patch chatterino 👌. Win in my book. Just needs to fix the tons of bugs I've left hanging in making this happen.

The things I did are linux specific but i'm sure the same philosophy can be done for the windows port. We know that chatterino updates the json files with the selected channels on close, so that was the focus here. The updated process is as such:

1. User **double clicks** on the desired chat tab
2. Chatterino switches to the new tab
3. Simultaneously, the 'Rename Tab' dialogue pops up
4. Because we have access to chatterino's PID since it's a child process, we continuously monitor the background for any new child dialogues that chatterino may make
5. A child dialogue was detected, and it was the 'Rename Tab' dialogue
6. Detach chatterino from its embedded container
7. Send the **Close** signal to all chatterino windows
8. When chatterino gracefully closes, it will update the json file
9. Read new channel and relaunch chatterino

Very annoying but very necessary. If chatterino is closed normally as a child process, it does not write to the json file which is very annoying. And since it's embedded, it doesn't have a 'window' to gracefully close. So it needs to be detached and have all its windows closed that way in order to make chatterino update the json file. 

Monitoring for the new dialogue popup for chatterino isn't necessary, but the convenience of just needing to double click a tab is more than worth it.

Lots of little bugs here, biggest is that once a tab is switched the app doesn't close appropriately. Easy fix to launch from terminal and kill from terminal, but will need to be bugged later.

Hope this helps on the windows side of things. Also would be easier if chatterino would write to debug file when they switch channels or add some sort of IPC for this app, but one can dream lol

**Comment by dewcked** [comment]
Thank you for your hard work, despite such a tricky task. I think it's the most optimal and simplest way to do it, except that you have to double-click it (unfortunately). 👍

**Comment by dewcked** [comment]
Now remaining works would be making everything run behind the window. Blocking draw calls using native function calls is necessary for that.

I played around with event filter thing and found out when double clicking channel prompts rename tab, MainWindow is deactivated and release signal is emitted.

Then we can mix this with global position of mouse click event, whether mouse is inside Chatterino at the time.

MainWindow constructor =

```
qApp->installEventFilter(this);
```

eventfilter = 

```
bool MainWindow::eventFilter(QObject *obj, QEvent *event)
{
  if (event->type() == QEvent::MouseButtonRelease && obj->isWindowType())
  {
    QMouseEvent *mouseEvent = static_cast<QMouseEvent *>(event);
    qDebug() << "Released!" << mouseEvent->button();
    qDebug() << event << obj;
    if (mouseEvent->button() == Qt::LeftButton)
    {
      qDebug() << mapToGlobal(ui->widget->pos()) << mouseEvent->globalPosition().toPoint();
      QPoint calc = mapToGlobal(ui->widget->pos()) - mouseEvent->globalPosition().toPoint();
      if (calc.x() < 0 && calc.y() < 0)
        qDebug() << "DETECTED";
    }
  }
}
```

EDIT: when `DETECTED` we can then just seperate the Chatterino window and restart it. (Much better solution imao)

So sad that linux version takes time to manipulate json file. 😢

**Comment by dewcked** [comment]
@JohnCiubuc I cleaned the fork repository a little bit. It works nicely.

**Comment by dewcked** [comment]
@JohnCiubuc I'm almost done with porting. I'm Closing this issue for now as no more debates needed. It's time to contribute to linux version ❤️
